### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [RomanGolub1/kinozal#1]
1)

В файлах установлены разные отступы.
Т.е. в каком-то файле установлены отступы в 2 пробела, в другом файле отступы составляют 4 пробела.
Допускается отступы или 2, или 4, количество отступов должно быть одинаковым для всех файлов проекта, включая HTML, CSS, JS, TS.
Использование символа табуляции, 1 / 3 / 5 / 6 / 7 пробелов в качестве отступов - запрещено.
Определитесь с количеством отступов и настройте их число для каждого файла отдельно, а также исправьте количество пробелов для новых файлов по умолчанию.
Как это сделать - описано в документации используемого вами редактора (вопрос гуглится).
После настройки отступов выполните автоматическое форматирование для всех файлов проекта.

![image](https://user-images.githubusercontent.com/8464662/142826329-e1b1f618-01d8-42ea-a2e0-498c4e367849.png)

2)
Нет скруглений по краям.
![image](https://user-images.githubusercontent.com/8464662/142826548-d88300fe-f2cd-427e-9368-7c90cb0a4aff.png)

3)
Некорректный вид элементов.
![image](https://user-images.githubusercontent.com/8464662/142826672-59f48318-0747-49db-8f57-521a2586117e.png)

4)
Некорректный вид элемента.
![image](https://user-images.githubusercontent.com/8464662/142826747-5c502d28-a0c1-4920-b1ee-5ce2641d6ad0.png)
![image](https://user-images.githubusercontent.com/8464662/142826802-53eabded-b338-4cd2-be96-b19fecb0d3d5.png)

**Comment by RomanGolub1** [comment]
Добрий день, зробив парвки на які ви вказали.
